
EOS 491/526 Assignment #3 

Daniel Scanks V00788200

Question #1

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
%matplotlib inline
import numpy.linalg as ag

print('solving overdetermined problem from Assignment 2, Question 1:')

#sensitivity matrix
A = np.matrix([[1.,1.,1.,1.,1.],[1.,1.,1.,1.,0.5],[1.,1.,1.,0.5,0],[1.,1.,0.5,0,0],[1.,0.5,0,0,0],[0.5,0,0,0,0]])
A_T = A.transpose()

#true model
m_t = np.matrix([1,2,3,4,5])
m_t = m_t.transpose()



#true data
d_t = np.matrix([15.,12.5,8.,4.5,2.,0.5])
d = d_t.transpose()

#calculating m with SVD
U,s,V_T = ag.svd(A) # SVD decomposition of A into components
one1 = np.dot(V_T.T,ag.inv(np.diag(s)))
U = np.delete(U,np.s_[-1:],1) #Making U NxM
pseudoinv_svd = np.dot(one1,U.T)
m= np.dot(pseudoinv_svd,d)
print('model solution using svd psuedoinverse:')
print m
print('Vs.')
print('least-squared-error solution from assignment 2:')
print(np.matrix([[1],[2],[3],[4],[5]]))
print('The SVD pseudo-inverse method does produce the same result as the least-squared-error method for an overdetermined problem')

print()
print('solving under-determined problem from Assignment 2, Question 1:')
#sensitivity matrix
A = np.matrix([[1.,1.,1.],[1.,1.,0]])
A_T = A.transpose()

#true model
mt = np.matrix([1.,2.,3.])
m_t = mt.transpose()

#true data
d_t = np.matrix([6.,3.])
d = d_t.transpose()

U,s,V_T = ag.svd(A) # SVD decomposition of A into components (s = lamda)
s = np.matrix([[2.13577921,0,],[0,0.66215345]]) #making s/Lamda into MxM diagonal matrix
invs = ag.inv(s)
invs = np.matrix([[ 0.46821319,0,0],[ 0, 1.51022395,0],[0,0,0]]) #Moore-Penrose
print('Moore-Penrose Inverse Lambda Matrix:')
print invs
one = np.dot(V_T.T,invs)
U = np.matrix([[-0.78820544,-0.61541221,0],[-0.61541221,0.78820544,0]]) #making U work for underdeterined calc
pseudoinv_svd = np.dot(one,U.T)
m= np.dot(pseudoinv_svd,d)
print('model solution using svd psuedoinverse:')
print m
print('Vs.')
print('smallest model solution from assignment 2:')
print(np.matrix([[1.5],[1.5],[3]]))
print('The SVD pseudo-inverse method does produce the same result as the smallest method for an underdetermined problem')


solving overdetermined problem from Assignment 2, Question 1:
model solution using svd psuedoinverse:
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]]
Vs.
least-squared-error solution from assignment 2:
[[1]
 [2]
 [3]
 [4]
 [5]]
The SVD pseudo-inverse method does produce the same result as the least-squared-error method for an overdetermined problem
()
solving under-determined problem from Assignment 2, Question 1:
Moore-Penrose Inverse Lambda Matrix:
[[ 0.46821319  0.          0.        ]
 [ 0.          1.51022395  0.        ]
 [ 0.          0.          0.        ]]
model solution using svd psuedoinverse:
[[ 1.5       ]
 [ 1.5       ]
 [ 2.99999998]]
Vs.
smallest model solution from assignment 2:
[[ 1.5]
 [ 1.5]
 [ 3. ]]
The SVD pseudo-inverse method does produce the same result as the smallest method for an underdetermined problem


Question 2

In [5]:
x = 500. #distance

# reciever depth values (m)
z = np.arange(10,110,10) 


#noise (s)
n= np.random.normal(0,0.0001,10)
n = np.matrix(n)
noise = n.T


#velocities (m/s)
v = np.matrix([1500.,1495.,1490.,1487.,1490.,1495.,1500.,1505.,1508.,1510.])
#slowness
m = np.array([1/1500.,1/1495.,1/1490.,1/1487.,1/1490.,1/1495.,1/1500.,1/1505.,1/1508.,1/1510.])
m = np.matrix(m)
m = m.T



#a square, even determined
print('a)')
#d = Am + n
#layer thicknesses
t = 10

# source at 0m
sin0 = np.zeros(10)
for i in range(0,10): 
    sin0[i] = abs(z[i])/(np.sqrt(x**2+(z[i])**2))


#Asquare
A0 = np.zeros((10,10))
for i in range(0,10):
    n= 0
    while(n < i+1):
        A0[i,n] = t/sin0[i]
        n= n+1
print A0

#data
d0 = np.dot(A0,m)
print('observed data for source at 0m')
d0_obs = d0 +noise
print d0_obs
#invert to find predicted model
 

def matrixPlot(Ai, normtype):
    #normtype 1 normalizes whole matrix
    #normtype 2 normalizes rows of matrix

    N, M = Ai.shape

    if(normtype == 1):
        norm = np.max(abs(Ai))
        A = Ai/(norm*2)
    elif(normtype == 2):
        A = Ai*1.
        for i in range(0, N, 1):
            norm = np.max(abs(Ai[i,]))
            A[i,] = Ai[i,]/(norm*2)

    t = np.arange(0, 10, 1)
    plt.figure()
    for i in range(0, N, 1):
        base = A[i,]*0.
        base.fill(N-i)
        plt.fill_between(t, base, A[i,]+base)
    plt.ylim(0,N+1)

print('b)')
# source at 50m
sin50 = np.zeros(10)
for i in range(0,10): 
    sin50[i] = abs(z[i]-50)/(np.sqrt(x**2+(z[i]-50)**2))

A50 = np.zeros((10,10))
for i in range(0,10):
    if i == 4:
        A50[i,i] = x
    else:
        n= 0
        while(n < i+1):
            A50[i,n] = t/sin50[i]
            n = n+1
print A50
#data
d50 = np.dot(A50,m)
print('observed data for source at 50m')
d50_obs = d50 +noise
print d50_obs
#invert to find predicted model

# source at 90m
sin90 = np.zeros(10)
for i in range(0,10): 
    sin90[i] = abs(z[i]-90)/(np.sqrt(x**2+(z[i]-90)**2))

A90 = np.zeros((10,10))
for i in range(0,10):
    if i == 8:
        A90[i,i] = x
    else:
        n= 0
        while(n < i+1):
            A90[i,n] = t/sin90[i]
            n= n+1
print A50
#data
d90 = np.dot(A90,m)
print('observed data for source at 90m')
d90_obs = d90 +noise
print d90_obs
#invert to find predicted model
    
    

a)
[[ 500.09999       0.            0.            0.            0.            0.
     0.            0.            0.            0.        ]
 [ 250.19992006  250.19992006    0.            0.            0.            0.
     0.            0.            0.            0.        ]
 [ 166.96639715  166.96639715  166.96639715    0.            0.            0.
     0.            0.            0.            0.        ]
 [ 125.39936204  125.39936204  125.39936204  125.39936204    0.            0.
     0.            0.            0.            0.        ]
 [ 100.49875621  100.49875621  100.49875621  100.49875621  100.49875621
     0.            0.            0.            0.            0.        ]
 [  83.93118875   83.93118875   83.93118875   83.93118875   83.93118875
    83.93118875    0.            0.            0.            0.        ]
 [  72.12517464   72.12517464   72.12517464   72.12517464   72.12517464
    72.12517464   72.12517464    0.            0.            0.        ]
 [  63.2949445